# Generated by Django 5.2.3 on 2025-06-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.publisher'),
        ),
    ]
