# Generated by Django 5.2.3 on 2025-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='films.genre'),
        ),
    ]
